name: crm_mvp_release

services:
  web:
    build: .
    restart: unless-stopped
    container_name: crm_web
    env_file:
      - .env
    environment:
      POSTGRES_HOST: crm_db
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app/media:/app/media
    networks:
      - crm_net

  worker:
    build: .
    restart: unless-stopped
    container_name: crm_worker
    command: python manage.py run_import_worker --poll-interval 2
    env_file:
      - .env
    environment:
      POSTGRES_HOST: crm_db
    volumes:
      - ./app/media:/app/media
    networks:
      - crm_net

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - crm_net

networks:
  crm_net:
    external: true
