# Generated by Django 5.2.12 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_company_city_company_country_company_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
