# Generated by Django 5.2.12 on 2026-03-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_company_address_alter_importrow_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
