# Generated by Django 5.2.12 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_bootstrap_crm_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitebranding",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="logo_image",
            field=models.ImageField(blank=True, upload_to="branding/"),
        ),
    ]
