# Generated by Django 5.2.12 on 2026-03-17

import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations


def _copy_legacy_import_uploads(old_dir, new_dir):
    copied_paths = {}
    if not old_dir.exists():
        return copied_paths

    new_dir.mkdir(parents=True, exist_ok=True)
    for old_path in old_dir.iterdir():
        if not old_path.is_file():
            continue

        new_path = new_dir / old_path.name
        if not new_path.exists():
            shutil.copy2(old_path, new_path)
        copied_paths[str(old_path)] = str(new_path)

    return copied_paths


def move_legacy_import_uploads(apps, schema_editor):
    ImportFile = apps.get_model("crm", "ImportFile")
    legacy_uploads_dir = Path(settings.BASE_DIR) / "data" / "uploads"
    media_uploads_dir = Path(settings.MEDIA_ROOT) / "imports"
    migrated_paths = _copy_legacy_import_uploads(legacy_uploads_dir, media_uploads_dir)

    if not migrated_paths:
        return

    for import_file in ImportFile.objects.exclude(source_path=""):
        new_path = migrated_paths.get(import_file.source_path)
        if new_path and import_file.source_path != new_path:
            import_file.source_path = new_path
            import_file.save(update_fields=["source_path"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_replace_brand_logo_url_with_image"),
    ]

    operations = [
        migrations.RunPython(move_legacy_import_uploads, migrations.RunPython.noop),
    ]
