# Generated by Django 5.2.12 on 2026-03-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_importfile_original_source_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactemail',
            options={'ordering': ('-is_primary', 'id')},
        ),
        migrations.AlterModelOptions(
            name='contactphone',
            options={'ordering': ('-is_primary', 'id')},
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='importrow',
            name='mapped_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
